default_settings: null
behaviors:
  MazeOne:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048  # Larger batch size could improve stability of learning
      buffer_size: 20480  # Increase buffer size proportional to batch size
      learning_rate: 0.0003  # Try different learning rates, if learning is too slow, increase this
      beta: 0.005  # Keep unchanged unless you find issues with exploration/exploitation balance
      epsilon: 0.2  # Keep unchanged unless you find issues with exploration/exploitation balance
      lambd: 0.95  # Keep unchanged unless there's a high variance in the return
      num_epoch: 5  # More epochs might improve learning at the cost of longer training time
      learning_rate_schedule: linear
    network_settings:
      normalize: true  # Normalizing inputs can often help with learning
      hidden_units: 512  # More hidden units can capture more complex functions, at the risk of overfitting
      num_layers: 3  # More layers can capture more complex functions, at the risk of overfitting
      vis_encode_type: simple 
    reward_signals:
      extrinsic:
        gamma: 0.99  # The closer to 1, the more the agent cares about long-term rewards
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
env_settings:
  base_port: 5005
  num_envs: 1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
checkpoint_settings:
  run_id: Test1
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: true
  inference: false
  results_dir: results
debug: false